# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_starter:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./Content/Starter
      run: dotnet restore
    - name: Build
      working-directory: ./Content/Starter
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./Content/Starter
      run: dotnet test --no-build --verbosity normal
  

  build_modularMonolith:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./Content/ModularMonolith
      run: dotnet restore
    - name: Build
      working-directory: ./Content/ModularMonolith
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./Content/ModularMonolith
      run: dotnet test --no-build --verbosity normal